# render.yaml - Place this in your root directory
services:
  - type: web
    name: chat-app-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: BETTER_AUTH_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false